[package]
name = "rpls-py"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rpls_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.1"
rpls = { git = "https://github.com/tph5595/rpls.git" }
